index/urls.py
from django.urls import path
from .views import index

app_name = "index"

urlpatterns = [
    path("", index, name="index"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls")),
    path("products/", include("products.urls")),
]

products/urls.py
from django.urls import path
from .views import index, new, show, edit, delete

app_name = "products"

urlpatterns = [
    path("", index, name="index"),
    path("new/", new, name="new"),
    path("<int:id>/", show, name="show"),
    path("<int:id>/edit", edit, name="edit"),
    path("<int:id>/delete", delete, name="delete"),
]

index/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(null=True, max_length=100)
    price = models.DecimalField(null=True, max_digits=10, decimal_places=2)
    description = models.TextField(null=True)

index/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .form import ProductForm
from .models import Product


def index(request):
    if request.POST:
        form = ProductForm(request.POST)
        form.save()
        return redirect("products:index")
    products = Product.objects.order_by("-id")
    return render(request, "products/index.html", {"products": products})


def new(request):
    form = ProductForm()
    return render(request, "products/new.html", {"form": form})


def show(request, id):
    product = get_object_or_404(Product, id=id)
    if request.POST:
        form = ProductForm(request.POST, instance=product)
        form.save()
        return redirect("products:show", id=product.id)
    return render(request, "products/show.html", {"product": product})


def edit(request, id):
    product = get_object_or_404(Product, id=id)
    form = ProductForm(instance=product)
    return render(request, "products/edit.html", {"product": product, "form": form})


def delete(request, id):
    product = get_object_or_404(Product, id=id)
    if request.POST:
        product.delete()
        return redirect("products:index")
    return render(request, "products/delete.html", {"product": product})

index/templates/index.html
{% extends "layout.html" %} {% block "content" %}
<h1>Hello</h1>
<a href="{% url "products:index" %}">前往商品列表</a>
<ul>
    {% for product in products%}
       <li><a href="{% url "products:show" product.id %}">{{ product.title }}</a></li>
    {% endfor %}   
</ul>
{% endblock %}

products/templates/products/delete.html
{% extends "layout.html" %} {% block "content" %}
<h1>確認刪除？</h1>
<form method="POST">
  {% csrf_token %}
  <button>刪除</button>
</form>
{% endblock %}

products/templates/products/edit.html
{% extends "layout.html" %} {% block "content" %}
<h1>編輯商品</h1>
<form action="{% url "products:show" product.id %}" method="POST">
    {{form.as_p}}
    <button>新增</button>
    {% csrf_token %}
</form>
{% endblock %}

products/templates/products/index.html
{% extends "layout.html" %} {% block "content" %}
<h1>Project List</h1>
<button><a href="{% url "products:new" %}">新增商品</a></button>
<ul>
    {% for product in products %}
        <li><a href="{% url "products:show" product.id %}">{{product.title}}</a></li>
    {% endfor %}
</ul>

{% endblock %}

products/templates/products/new.html
{% extends "layout.html" %} {% block "content" %}
<h1>新增商品</h1>
<form action="{% url "products:index" %}" method="POST">
    {{ form.as_p }}
    <button>新增</button>
    {% csrf_token %}
</form>
{% endblock %}

products/templates/products/show.html
{% extends "layout.html" %} {% block "content" %}
<h1>{{product.title}}</h1>
<h1>{{product.price}}</h1>
<h1>{{product.description}}</h1>
<button><a href="{% url "products:edit" product.id %}">編輯</a></button>
<button><a href="{% url "products:delete" product.id %}">刪除</a></button>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    {% block "content" %} {% endblock %}
  </head>
  <body></body>
</html>